### ISSUE TITLE
eks-orbs is not working for windows application

### ISSUE THREAD

**Issue by jitendramalan7** [CircleCI-Public/aws-eks-orb#27]
eks-orbs is not working for windows application. After deploying the windows docker image to ECR, the build is failed while installing KOPS.

**Comment by lokst** [comment]
@jitendramalan7 Thanks for filing this issue. The EKS orb has not yet been tested for compatibility with the Windows docker image but we'd like to address that.

**Comment by jitendramalan7** [comment]
Is there any way to achieve automatic deployment using CircleCI for windows docker images?
Please suggest.

**Comment by lokst** [comment]
I believe most of the aspects of the EKS orb that are incompatible when executed on Windows are the installation commands. So I would recommend trying to install the dependencies before invoking the orb, like in the following example. KOPS installation can be skipped with the `skip-kubectl-install` flag set to `true`.


```
version: 2.1

orbs:
  win: circleci/windows@1.0.0
  aws-eks: circleci/aws-eks@0.2.6

jobs:
  build:
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            chocolatey install kubernetes-cli
            chocolatey install aws-iam-authenticator
            chocolatey install eksctl
      - aws-eks/create-cluster:
          cluster-name: my-eks-demo-win
          skip-kubectl-install: true
      - aws-eks/delete-cluster:
          cluster-name: my-eks-demo-win
```
