### ISSUE TITLE
awscli 2.0 support

### ISSUE THREAD

**Issue by bensternlieb** [CircleCI-Public/aws-eks-orb#29]
## What would you like to be added

Folks, I'm seeing an install of awscli 1.x after explicitly installing awscli 2.0.  Can a check be done first for existing awscli install?
```
orbs:
  aws-cli: circleci/aws-cli@1.0.0
  aws-eks: circleci/aws-eks@0.2.7

jobs:
  test:
    executor: aws-eks/python3
    steps:
      - checkout
      - aws-cli/setup
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: dl-k8s
          install-kubectl: true
```

## Why is this needed
Overhead of additional aws install is large and unnecessary.
