### ISSUE TITLE
Allow parameters to be configured through env vars

### ISSUE THREAD

**Issue by robinvdvleuten** [CircleCI-Public/aws-eks-orb#41]
## What would you like to be added

I would like to use the `update-kubeconfig-with-authenticator` command, but the only way to pass configuration like `AWS_REGION` is through parameters. It would be a great addition if the orb commands can also be configured through env vars.

## Why is this needed

We have configured a context per environment and pass the context of the correct environment to the jobs. Through the context, all correct env vars will be populated.

**Comment by brivu** [comment]
Hey @robinvdvleuten, 

As it stands today, you are able to add environment variables and use them in your config.  

For example in the snippet below, $AWS_DEFAULT_REGION is an environment variable you set through your project settings in CircleCI (Project Settings > Environment Variables).  

```
 - test-update-kubeconfig:
          name: test-update-kubeconfig_region-<< matrix.executor >>
          cluster-name: ${AWS_RESOURCE_NAME_PREFIX}-orb-test-defaults-<< matrix.executor >>
          context: [CPE_ORBS_AWS]
          region: $AWS_DEFAULT_REGION
```

Let me know if that helps with what you are looking for.  I'm going to close out this issue but feel free to ping me and reopen if this doesn't help. 

Best, 
Brian
