### ISSUE TITLE
Cannot find a definition for executor named python

### ISSUE THREAD

**Issue by vlesich-sylabs** [CircleCI-Public/aws-eks-orb#52]
### Orb version

2.0

### What happened

```
#!/bin/sh -eo pipefail
# Error calling workflow: 'deployment'
# Error calling job: 'aws-eks/update-container-image'
# Cannot find a definition for executor named python
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
```

### Expected behavior

Should proceed without any errors 

---

Here is the example of configs that I used

```
version: '2.1'
orbs:
  aws-eks: circleci/aws-eks@2.0  
workflows:
  deployment:
    jobs:
      - aws-eks/update-container-image:
          cluster-name: staging-eks
          aws-region: us-east-1
          container-image-updates: 'nginx=nginx:1.9.1'
          resource-name: deployment/nginx-deployment
          namespace: citestns
          show-kubectl-command: true
          watch-rollout-status: true
          get-rollout-status: true
```

the same configs with orb version **1.2.0** works without any problems

**Comment by Tybot204** [comment]
Also seeing the same issue. I notice the `executors` folder with all Python executors is missing in version 2.0. Unsure if this is intended or if this got lost in a merge somewhere though.

**Comment by brivu** [comment]
Hey @vlesich-sylabs  and @Tybot204, 

Thanks for the ping, I really appreciate it.  Version 1 of this orb had an executor folder which contained old images of python that will no longer be supported by the end of the year. The folder was omitted on purpose for version 2. 

All images with the `circleci` namespace will be deprecated.  New images will have the `cimg` namespace.  You can find a list of maintained images [here](https://circleci.com/developer/images)

For version 2, I've defined the latest image of python 3 ([link here](https://github.com/CircleCI-Public/aws-eks-orb/blob/6ca33e02f984ea02d6b37c974a9edc502e0a7c8a/.circleci/config.yml#L91)) and others using the `executors` parameter in my config file:

```
executors:
  docker:
    docker:
      - image: cimg/base:stable
  macos:
    macos:
      xcode: 13.2.0
  machine:
    machine:
      image: ubuntu-2004:202107-02
  python:
    docker:
      - image: cimg/python:3.10-browsers
```

And then in the `aws-eks/update-container-image` job, I referenced the executor using the `executor` parameter:
```
- aws-eks/update-container-image:
          name: update-container-image-kubectl-<< matrix.executor >>
          cluster-name: ${AWS_RESOURCE_NAME_PREFIX}-eks-orb-test-kubectl-<< matrix.executor >>
          context: [CPE_ORBS_AWS]
          executor: python
          aws-region: "us-west-2"
          resource-name: "deployment/nginx-deployment"
          container-image-updates: "nginx=nginx:1.9.1"
```

I'm going to close this for now but feel free to reopen if you need more assistance.  

Best, 
Brian

**Comment by vlesich-sylabs** [comment]
@brivu it's not apparent at all. You need to update the documentation of this Orb to show how to use it https://circleci.com/developer/orbs/orb/circleci/aws-eks because currently this documentation is invalid, and there are no mentions about this new way of how to use this Orb.

**Comment by brivu** [comment]
Hey @vlesich-sylabs, 

Good point.  Let me go ahead and update these usage examples now.  Apologies for the confusion.

Best, 
Brian

**Comment by brivu** [comment]
Hey @vlesich-sylabs and @Tybot204, 

This is being addressed in PR https://github.com/CircleCI-Public/aws-eks-orb/pull/54.  In addition to the example I gave you above, you can also add the image you'd like to use directly in a job definition like so: 
```
  jobs:
    test-cluster:
      docker:   # Referencing the python image here
        - image: cimg/python:3.10 
      parameters:
        cluster-name:
          description: |
            Name of the EKS cluster
          type: string
      steps:
        - kubernetes/install
        - aws-eks/update-kubeconfig-with-authenticator:
            cluster-name: << parameters.cluster-name >>
        - run:
            name: Test cluster
            command: |
              kubectl get services
```

I've added the changes to the usage examples and just wanted to make a note here.  Again, apologies for the confusion.  Thanks for the ping and please let me know if there's anything else you need! 

Best. 
Brian
