### ISSUE TITLE
invalid apiVersion

### ISSUE THREAD

**Issue by robrichardson13** [CircleCI-Public/aws-eks-orb#67]
### Orb version
aws-eks: circleci/aws-eks@2.1.2
kubernetes: circleci/kubernetes@1.3

### What happened
We just started getting this error when running `kubectl` commands:
```sh
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```

```sh
  my-job:
    docker:
      - image: 'cimg/python:3.10'
    parameters:
      cluster-name:
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl version
          name: My Job
```

### Expected behavior

The `kubectl` command should work, but instead its erroring on every command.

**Comment by DanielFrank** [comment]
The issue is that kubernetes released v1.24 whose kubectl deprecated `client.authentication.k8s.io/v1alpha1`.

So `circleci/kubernetes@1.3` installs the latest Kubernetes and then this orb tries to run  `client.authentication.k8s.io/v1alpha1` which is now deprecated. Thus the error.

Unfortunately, we can't specify version numbers in `update-kubeconfig-with-authenticator` (which installs kubernetes).

A workaround is to run `install-kubectl` with a version number and then run  `update-kubeconfig-with-authenticator` 
 with `install-kubectl` set to false.

Long-term solution is for this guy to not use `client.authentication.k8s.io/v1alpha1`.

**Comment by robrichardson13** [comment]
Thanks @DanielFrank! Implemented this with this job config:

```yaml
  my-job:
    docker:
      - image: 'cimg/python:3.10'
    parameters:
      cluster-name:
        type: string
    steps:
      - kubernetes/install-kubectl:
          kubectl-version: v1.23.0
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: false
      - run:
          command: |
            kubectl version
          name: My Job
```

**Comment by DanielFrank** [comment]
@robrichardson13 Please don't close it. We need this fixed!

**Comment by DanielFrank** [comment]
The relevant release note for v1.24 is [here](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.24/release-notes/release-notes-draft.json#L5477-L5478)

**Comment by DanielFrank** [comment]
If I'm reading the [code correctly](https://github.com/CircleCI-Public/aws-eks-orb/blob/master/src/scripts/update-kubeconfig-with-authenticator.sh#L36), the orb just runs `aws eks update-kubeconfig "$@"` so this may be an aws issue.

**Comment by DanielFrank** [comment]
Looking at https://github.com/aws/eks-distro, they only claim to work from v1.19-v1.22. So we may have to do the short-term fix.
![Screen Shot 2022-05-03 at 7 20 32 PM](https://user-images.githubusercontent.com/6756725/166606420-c6b652a1-67d9-4f55-838f-44d702327055.png)

**Comment by chrisdmacrae** [comment]
This is a problem with any command of any package implementing the `aws-eks/update-kubeconfig-with-authenticator` step.

I.e, we use `aws-eks/update-container-image` which always calls `aws-eks/update-kubeconfig-with-authenticator` with `install-kubectl: true`. We need to be able to override this to not install kubectl again.

**Comment by caraways** [comment]
We see the same error. We run kubectl exec commands from circle ci against our aws eks cluster 1.19.  We need to be able to specify the version of kubectl installed to match what is supported by AWS EKS.

**Comment by wasims1** [comment]
To anyone coming here from google (i feel my specialty now is writing these things for circleci orbs!), here's how you fix your pipeline if you getting the error `error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"`

It's basically because k8s just released a new version May 3rd 2022, so you need to fix the kubectl version like this (change to your version) and voila - also make sure you indent your yaml properly:

``` - kubernetes/install-kubectl: #newest kubectl is not compatible with authenticator version and will throw an error otherwise
          kubectl-version: v1.21.0
          max-time: false #This parameter will enable the curl command to not timeout for 600 seconds
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: ${AWS_REGION}
          install-kubectl: false #this is false by default, but make sure you dont' have it as true

**Comment by anthonycrobinson** [comment]
I'm not sure how to cause a development version to be create to cause integration tests for the above PR.
Example of what this provides to fix the issue:
```
    - aws-eks/update-container-image:
        name: my-app
        cluster-name: cluster-name
        namespace: app-namespace
        aws-region: us-east-1
        resource-name: deployment/myapp
        container-image-updates: "nginx=nginx:1.9.1"
        kubectl-version: v1.21.0
```
